document.addEventListener("DOMContentLoaded",function(){{var e=document.createElement("link");e.href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap",e.rel="stylesheet",document.head.appendChild(e);const s=()=>{var e=Date.now().toString(36),t=Math.random().toString(36).substring(2,8),l=(s.counter=(s.counter||0)+1,s.counter.toString(36));return e+`-${t}-`+l},a=s(),n=((e=document.createElement("link")).href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css",e.rel="stylesheet",document.head.appendChild(e),e=document.createElement("div"),document.createElement("div"));e.style.position="fixed",e.style.bottom="30px",e.style.right="30px",e.style.width="80px",e.style.height="80px",e.style.borderRadius="50%",e.style.display="flex",e.style.alignItems="center",e.style.justifyContent="center",e.style.cursor="pointer";var t=document.createElement("img"),t;t.src="https://img.animalaria.cl/general/is-sparkle.png",t.alt="Chat",t.style.width="60px",t.style.height="60px",t.style.borderRadius="50%",t.style.backgroundColor="white",t.style.padding="5px",e.appendChild(t),n.style.position="fixed",n.style.bottom="110px",n.style.right="30px",n.style.width="700px",n.style.height="550px",n.style.backgroundColor="#F9F9F9",n.style.border="1px solid #E0E0E0",n.style.borderRadius="12px",n.style.boxShadow="0px 4px 16px rgba(0, 0, 0, 0.1)",n.style.display="none",n.style.flexDirection="column",n.style.overflow="hidden",n.style.fontFamily="'Poppins', sans-serif",(t=document.createElement("div")).style.backgroundColor="#0088cc",t.style.color="#ffffff",t.style.padding="15px",t.style.textAlign="center",t.style.fontWeight="bold",t.style.borderBottom="1px solid #E0E0E0",t.style.fontSize="16px",t.style.fontFamily="'Poppins', sans-serif",t.textContent="Asesor de Ventas";const r=document.createElement("div");r.style.flex="1",r.style.padding="15px",r.style.overflowY="auto",r.style.fontSize="14px",r.style.color="#4A4A4A",r.style.fontFamily="'Poppins', sans-serif",r.style.position="relative",r.style.setProperty("scrollbar-width","thin"),r.style.setProperty("scrollbar-color","#b3b3b3 #f0f0f0");var l=document.createElement("style");l.textContent=`
      div::-webkit-scrollbar {
        width: 8px;
      }
      div::-webkit-scrollbar-thumb {
        background-color: #b3b3b3;
        border-radius: 10px;
      }
      div::-webkit-scrollbar-track {
        background-color: #f0f0f0;
        border-radius: 10px;
      }
    `,document.head.appendChild(l);const i=document.createElement("div"),p=(i.style.position="absolute",i.style.top="50%",i.style.left="50%",i.style.transform="translate(-50%, -50%)",i.style.fontSize="64px",i.style.color="#E0E0E0",i.innerHTML='<i class="fas fa-comments"></i>',r.appendChild(i),(l=document.createElement("div")).style.display="flex",l.style.borderTop="1px solid #E0E0E0",document.createElement("input")),c=(p.type="text",p.placeholder="Escribe un mensaje...",p.style.flex="1",p.style.border="none",p.style.padding="15px",p.style.fontSize="14px",p.style.outline="none",p.style.fontFamily="'Poppins', sans-serif",p.addEventListener("input",()=>{100<p.value.length&&(p.value=p.value.slice(0,100))}),document.createElement("button")),y=(c.textContent="Enviar",c.style.border="none",c.style.backgroundColor="#0088cc",c.style.color="#ffffff",c.style.padding="15px",c.style.cursor="pointer",c.style.fontFamily="'Poppins', sans-serif",document.createElement("div"));y.textContent="Consultando",y.style.display="none",y.style.textAlign="center",y.style.marginTop="10px",y.style.color="#0088cc",y.style.fontFamily="'Poppins', sans-serif",l.appendChild(p),l.appendChild(c),n.appendChild(t),n.appendChild(r),n.appendChild(y),n.appendChild(l),e.addEventListener("click",()=>{n.style.display="none"===n.style.display?"flex":"none","flex"===n.style.display&&p.focus()});let d;const o=()=>{var l=p.value.trim();if(l){i.style.display="none";var s=document.createElement("div");s.textContent=l,s.style.margin="5px 0",s.style.padding="10px",s.style.backgroundColor="#d1f3ff",s.style.borderRadius="8px",r.appendChild(s),r.scrollTop=r.scrollHeight,p.value="";const n=document.createElement("div");n.style.margin="5px 0",n.style.padding="10px",n.style.backgroundColor="#A2D2FF",n.style.color="#4A4A4A",n.style.borderRadius="8px",n.style.whiteSpace="pre-wrap",r.appendChild(n),r.scrollTop=r.scrollHeight,y.style.display="block",p.disabled=!0,c.disabled=!0;let e="";d=setInterval(()=>{e=e.length<3?e+".":"",y.textContent="Consultando"+e},500);const o=new EventSource(`https://assistant-ai-mu.vercel.app/v1/ask/assistant?question=${encodeURIComponent(l)}&assistant_id=ba939fe0-3304-4377-afd2-2153f0a77568&client_id=`+a);let t="";o.addEventListener("textDelta",e=>{e=(t+=e.data).replace(/`/g,"").replace(/html/gi,"");n.innerHTML=e,r.scrollTop=r.scrollHeight}),o.addEventListener("end",()=>{o.close(),clearInterval(d),y.style.display="none",p.disabled=!1,c.disabled=!1,p.focus()}),o.addEventListener("error",()=>{var e=document.createElement("div");e.textContent="Error al obtener respuesta",e.style.margin="5px 0",e.style.padding="10px",e.style.backgroundColor="#f8d7da",e.style.color="#721c24",e.style.borderRadius="4px",r.appendChild(e),r.scrollTop=r.scrollHeight,o.close(),clearInterval(d),y.style.display="none",p.disabled=!1,c.disabled=!1,p.focus()})}};c.addEventListener("click",o),p.addEventListener("keypress",e=>{"Enter"===e.key&&o()}),document.body.appendChild(e),document.body.appendChild(n)}});