document.addEventListener("DOMContentLoaded",function(){{var e;(e=document.createElement("link")).href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap",e.rel="stylesheet",document.head.appendChild(e);var e,e=((e=document.createElement("link")).href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css",e.rel="stylesheet",document.head.appendChild(e),document.createElement("div"));const s=document.createElement("div");e.style.position="fixed",e.style.bottom="30px",e.style.right="30px",e.style.width="80px",e.style.height="80px",e.style.borderRadius="50%",e.style.display="flex",e.style.alignItems="center",e.style.justifyContent="center",e.style.cursor="pointer";var t=document.createElement("img"),t;t.src="https://img.animalaria.cl/general/is-sparkle.png",t.alt="Chat",t.style.width="60px",t.style.height="60px",t.style.borderRadius="50%",t.style.backgroundColor="white",t.style.padding="5px",e.appendChild(t),s.style.position="fixed",s.style.bottom="110px",s.style.right="30px",s.style.width="700px",s.style.height="550px",s.style.backgroundColor="#F9F9F9",s.style.border="1px solid #E0E0E0",s.style.borderRadius="12px",s.style.boxShadow="0px 4px 16px rgba(0, 0, 0, 0.1)",s.style.display="none",s.style.flexDirection="column",s.style.overflow="hidden",s.style.fontFamily="'Poppins', sans-serif",(t=document.createElement("div")).style.backgroundColor="#0088cc",t.style.color="#ffffff",t.style.padding="15px",t.style.textAlign="center",t.style.fontWeight="bold",t.style.borderBottom="1px solid #E0E0E0",t.style.fontSize="16px",t.style.fontFamily="'Poppins', sans-serif",t.textContent="Asesor de Ventas";const a=document.createElement("div");a.style.flex="1",a.style.padding="15px",a.style.overflowY="auto",a.style.fontSize="14px",a.style.color="#4A4A4A",a.style.fontFamily="'Poppins', sans-serif",a.style.position="relative",a.style.setProperty("scrollbar-width","thin"),a.style.setProperty("scrollbar-color","#b3b3b3 #f0f0f0");var l=document.createElement("style");l.textContent=`
      div::-webkit-scrollbar {
        width: 8px;
      }
      div::-webkit-scrollbar-thumb {
        background-color: #b3b3b3;
        border-radius: 10px;
      }
      div::-webkit-scrollbar-track {
        background-color: #f0f0f0;
        border-radius: 10px;
      }
    `,document.head.appendChild(l);const i=document.createElement("div"),r=(i.style.position="absolute",i.style.top="50%",i.style.left="50%",i.style.transform="translate(-50%, -50%)",i.style.fontSize="64px",i.style.color="#E0E0E0",i.innerHTML='<i class="fas fa-comments"></i>',a.appendChild(i),(l=document.createElement("div")).style.display="flex",l.style.borderTop="1px solid #E0E0E0",document.createElement("input")),p=(r.type="text",r.placeholder="Escribe un mensaje...",r.style.flex="1",r.style.border="none",r.style.padding="15px",r.style.fontSize="14px",r.style.outline="none",r.style.fontFamily="'Poppins', sans-serif",r.addEventListener("input",()=>{100<r.value.length&&(r.value=r.value.slice(0,100))}),document.createElement("button")),c=(p.textContent="Enviar",p.style.border="none",p.style.backgroundColor="#0088cc",p.style.color="#ffffff",p.style.padding="15px",p.style.cursor="pointer",p.style.fontFamily="'Poppins', sans-serif",document.createElement("div"));c.textContent="Consultando",c.style.display="none",c.style.textAlign="center",c.style.marginTop="10px",c.style.color="#0088cc",c.style.fontFamily="'Poppins', sans-serif",l.appendChild(r),l.appendChild(p),s.appendChild(t),s.appendChild(a),s.appendChild(c),s.appendChild(l),e.addEventListener("click",()=>{s.style.display="none"===s.style.display?"flex":"none","flex"===s.style.display&&r.focus()});let d;const n=()=>{var l=r.value.trim();if(l){i.style.display="none";var s=document.createElement("div");s.textContent=l,s.style.margin="5px 0",s.style.padding="10px",s.style.backgroundColor="#d1f3ff",s.style.borderRadius="8px",a.appendChild(s),a.scrollTop=a.scrollHeight,r.value="";const n=document.createElement("div");n.style.margin="5px 0",n.style.padding="10px",n.style.backgroundColor="#A2D2FF",n.style.color="#4A4A4A",n.style.borderRadius="8px",n.style.whiteSpace="pre-wrap",a.appendChild(n),a.scrollTop=a.scrollHeight,c.style.display="block",r.disabled=!0,p.disabled=!0;let e="";d=setInterval(()=>{e=e.length<3?e+".":"",c.textContent="Consultando"+e},500);const o=new EventSource(`https://assistant-ai-mu.vercel.app/v1/ask/assistant?question=${encodeURIComponent(l)}&assistant_id=6aaadf7d-6490-4d75-942a-bbd6851bca40`);let t="";o.addEventListener("textDelta",e=>{e=(t+=e.data).replace(/`/g,"").replace(/html/gi,"");n.innerHTML=e,a.scrollTop=a.scrollHeight}),o.addEventListener("end",()=>{o.close(),clearInterval(d),c.style.display="none",r.disabled=!1,p.disabled=!1,r.focus()}),o.addEventListener("error",()=>{var e=document.createElement("div");e.textContent="Error al obtener respuesta",e.style.margin="5px 0",e.style.padding="10px",e.style.backgroundColor="#f8d7da",e.style.color="#721c24",e.style.borderRadius="4px",a.appendChild(e),a.scrollTop=a.scrollHeight,o.close(),clearInterval(d),c.style.display="none",r.disabled=!1,p.disabled=!1,r.focus()})}};p.addEventListener("click",n),r.addEventListener("keypress",e=>{"Enter"===e.key&&n()}),document.body.appendChild(e),document.body.appendChild(s)}});
